version: '3'
services:
  wot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  wot-backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock