### GET TD
GET {{url}}

### GET properties
GET {{url}}/properties

### PUT temperature
PUT /test-device/properties/temperature HTTP/1.1
Host: http://localhost:8080
Content-Type: application/json

50

### GET temperature
GET {{url}}/properties/temperature

### Action
POST {{url}}/actions/setTemperature?temperature=45

### subscribe Event
GET http://localhost:8080/test-device/events/temperatureSet
# todo: set timeout to 0 to keep connection open
