### GET TD
GET {{url}}

### GET properties
GET {{url}}/properties

### make request
POST {{url}}/actions/make_request?method=GET&url=http://localhost:3000/test-device/properties/temperature

### PUT temperature
PUT {{url}}/properties/temperature HTTP/1.1
Content-Type: application/json

50

### GET temperature
GET {{url}}/properties/temperature

### Action
POST {{url}}/actions/setTemperature?temperature=45

### subscribe Event
GET {{url}}/events/temperatureSet
# todo: set timeout to 0 to keep connection open

### shutdown
# POST {{url}}/actions/shutdown
